/*
 * GitLab API
 * An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for APIEntitiesCommit
 */
public class APIEntitiesCommitTest {
    private final APIEntitiesCommit model = new APIEntitiesCommit();

    /**
     * Model tests for APIEntitiesCommit
     */
    @Test
    public void testAPIEntitiesCommit() {
        // TODO: test APIEntitiesCommit
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'shortId'
     */
    @Test
    public void shortIdTest() {
        // TODO: test shortId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'parentIds'
     */
    @Test
    public void parentIdsTest() {
        // TODO: test parentIds
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'authorName'
     */
    @Test
    public void authorNameTest() {
        // TODO: test authorName
    }

    /**
     * Test the property 'authorEmail'
     */
    @Test
    public void authorEmailTest() {
        // TODO: test authorEmail
    }

    /**
     * Test the property 'authoredDate'
     */
    @Test
    public void authoredDateTest() {
        // TODO: test authoredDate
    }

    /**
     * Test the property 'committerName'
     */
    @Test
    public void committerNameTest() {
        // TODO: test committerName
    }

    /**
     * Test the property 'committerEmail'
     */
    @Test
    public void committerEmailTest() {
        // TODO: test committerEmail
    }

    /**
     * Test the property 'committedDate'
     */
    @Test
    public void committedDateTest() {
        // TODO: test committedDate
    }

    /**
     * Test the property 'trailers'
     */
    @Test
    public void trailersTest() {
        // TODO: test trailers
    }

    /**
     * Test the property 'webUrl'
     */
    @Test
    public void webUrlTest() {
        // TODO: test webUrl
    }

}
