/*
 * GitLab API
 * An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BulkimportsStartNewMigrationRequest
 */
public class BulkimportsStartNewMigrationRequestTest {
    private final BulkimportsStartNewMigrationRequest model = new BulkimportsStartNewMigrationRequest();

    /**
     * Model tests for BulkimportsStartNewMigrationRequest
     */
    @Test
    public void testBulkimportsStartNewMigrationRequest() {
        // TODO: test BulkimportsStartNewMigrationRequest
    }

    /**
     * Test the property 'configurationUrl'
     */
    @Test
    public void configurationUrlTest() {
        // TODO: test configurationUrl
    }

    /**
     * Test the property 'configurationAccessToken'
     */
    @Test
    public void configurationAccessTokenTest() {
        // TODO: test configurationAccessToken
    }

    /**
     * Test the property 'entitiesSourceType'
     */
    @Test
    public void entitiesSourceTypeTest() {
        // TODO: test entitiesSourceType
    }

    /**
     * Test the property 'entitiesSourceFullPath'
     */
    @Test
    public void entitiesSourceFullPathTest() {
        // TODO: test entitiesSourceFullPath
    }

    /**
     * Test the property 'entitiesDestinationNamespace'
     */
    @Test
    public void entitiesDestinationNamespaceTest() {
        // TODO: test entitiesDestinationNamespace
    }

    /**
     * Test the property 'entitiesDestinationSlug'
     */
    @Test
    public void entitiesDestinationSlugTest() {
        // TODO: test entitiesDestinationSlug
    }

    /**
     * Test the property 'entitiesDestinationName'
     */
    @Test
    public void entitiesDestinationNameTest() {
        // TODO: test entitiesDestinationName
    }

    /**
     * Test the property 'entitiesMigrateProjects'
     */
    @Test
    public void entitiesMigrateProjectsTest() {
        // TODO: test entitiesMigrateProjects
    }

}
