/*
 * GitLab API
 * An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PlanlimitsModifyLimitsRequest
 */
public class PlanlimitsModifyLimitsRequestTest {
    private final PlanlimitsModifyLimitsRequest model = new PlanlimitsModifyLimitsRequest();

    /**
     * Model tests for PlanlimitsModifyLimitsRequest
     */
    @Test
    public void testPlanlimitsModifyLimitsRequest() {
        // TODO: test PlanlimitsModifyLimitsRequest
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

    /**
     * Test the property 'ciPipelineSize'
     */
    @Test
    public void ciPipelineSizeTest() {
        // TODO: test ciPipelineSize
    }

    /**
     * Test the property 'ciActiveJobs'
     */
    @Test
    public void ciActiveJobsTest() {
        // TODO: test ciActiveJobs
    }

    /**
     * Test the property 'ciProjectSubscriptions'
     */
    @Test
    public void ciProjectSubscriptionsTest() {
        // TODO: test ciProjectSubscriptions
    }

    /**
     * Test the property 'ciPipelineSchedules'
     */
    @Test
    public void ciPipelineSchedulesTest() {
        // TODO: test ciPipelineSchedules
    }

    /**
     * Test the property 'ciNeedsSizeLimit'
     */
    @Test
    public void ciNeedsSizeLimitTest() {
        // TODO: test ciNeedsSizeLimit
    }

    /**
     * Test the property 'ciRegisteredGroupRunners'
     */
    @Test
    public void ciRegisteredGroupRunnersTest() {
        // TODO: test ciRegisteredGroupRunners
    }

    /**
     * Test the property 'ciRegisteredProjectRunners'
     */
    @Test
    public void ciRegisteredProjectRunnersTest() {
        // TODO: test ciRegisteredProjectRunners
    }

    /**
     * Test the property 'conanMaxFileSize'
     */
    @Test
    public void conanMaxFileSizeTest() {
        // TODO: test conanMaxFileSize
    }

    /**
     * Test the property 'enforcementLimit'
     */
    @Test
    public void enforcementLimitTest() {
        // TODO: test enforcementLimit
    }

    /**
     * Test the property 'genericPackagesMaxFileSize'
     */
    @Test
    public void genericPackagesMaxFileSizeTest() {
        // TODO: test genericPackagesMaxFileSize
    }

    /**
     * Test the property 'helmMaxFileSize'
     */
    @Test
    public void helmMaxFileSizeTest() {
        // TODO: test helmMaxFileSize
    }

    /**
     * Test the property 'mavenMaxFileSize'
     */
    @Test
    public void mavenMaxFileSizeTest() {
        // TODO: test mavenMaxFileSize
    }

    /**
     * Test the property 'notificationLimit'
     */
    @Test
    public void notificationLimitTest() {
        // TODO: test notificationLimit
    }

    /**
     * Test the property 'npmMaxFileSize'
     */
    @Test
    public void npmMaxFileSizeTest() {
        // TODO: test npmMaxFileSize
    }

    /**
     * Test the property 'nugetMaxFileSize'
     */
    @Test
    public void nugetMaxFileSizeTest() {
        // TODO: test nugetMaxFileSize
    }

    /**
     * Test the property 'pypiMaxFileSize'
     */
    @Test
    public void pypiMaxFileSizeTest() {
        // TODO: test pypiMaxFileSize
    }

    /**
     * Test the property 'terraformModuleMaxFileSize'
     */
    @Test
    public void terraformModuleMaxFileSizeTest() {
        // TODO: test terraformModuleMaxFileSize
    }

    /**
     * Test the property 'storageSizeLimit'
     */
    @Test
    public void storageSizeLimitTest() {
        // TODO: test storageSizeLimit
    }

    /**
     * Test the property 'pipelineHierarchySize'
     */
    @Test
    public void pipelineHierarchySizeTest() {
        // TODO: test pipelineHierarchySize
    }

}
