/*
 * GitLab API
 * An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.APIEntitiesBatchedBackgroundMigration;
import com.konfigthis.client.model.BatchedbackgroundmigrationsPauseMigrationRequest;
import com.konfigthis.client.model.BatchedbackgroundmigrationsResumeMigrationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchedBackgroundMigrationsApi
 */
@Disabled
public class BatchedBackgroundMigrationsApiTest {

    private static BatchedBackgroundMigrationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BatchedBackgroundMigrationsApi(apiClient);
    }

    /**
     * Retrieve a batched background migration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMigrationTest() throws ApiException {
        Integer id = null;
        String database = null;
        APIEntitiesBatchedBackgroundMigration response = api.getMigration(id)
                .database(database)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the list of batched background migrations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String database = null;
        List<APIEntitiesBatchedBackgroundMigration> response = api.list()
                .database(database)
                .execute();
        // TODO: test validations
    }

    /**
     * Pause a batched background migration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pauseMigrationTest() throws ApiException {
        Integer id = null;
        String database = null;
        APIEntitiesBatchedBackgroundMigration response = api.pauseMigration(id)
                .database(database)
                .execute();
        // TODO: test validations
    }

    /**
     * Resume a batched background migration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resumeMigrationTest() throws ApiException {
        Integer id = null;
        String database = null;
        APIEntitiesBatchedBackgroundMigration response = api.resumeMigration(id)
                .database(database)
                .execute();
        // TODO: test validations
    }

}
