/*
 * GitLab API
 * An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.APIEntitiesBulkImport;
import com.konfigthis.client.model.APIEntitiesBulkImports;
import com.konfigthis.client.model.BulkimportsStartNewMigrationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BulkImportsApi
 */
@Disabled
public class BulkImportsApiTest {

    private static BulkImportsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BulkImportsApi(apiClient);
    }

    /**
     * Get GitLab Migration entity details
     *
     * This feature was introduced in GitLab 14.1.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEntityDetailsTest() throws ApiException {
        Integer importId = null;
        Integer entityId = null;
        APIEntitiesBulkImports response = api.getEntityDetails(importId, entityId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get GitLab Migration details
     *
     * This feature was introduced in GitLab 14.1.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMigrationDetailsTest() throws ApiException {
        Integer importId = null;
        APIEntitiesBulkImport response = api.getMigrationDetails(importId)
                .execute();
        // TODO: test validations
    }

    /**
     * List GitLab Migration entities
     *
     * This feature was introduced in GitLab 14.1.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEntitiesTest() throws ApiException {
        Integer importId = null;
        String status = null;
        Integer page = null;
        Integer perPage = null;
        List<APIEntitiesBulkImports> response = api.listEntities(importId)
                .status(status)
                .page(page)
                .perPage(perPage)
                .execute();
        // TODO: test validations
    }

    /**
     * List all GitLab Migrations&#39; entities
     *
     * This feature was introduced in GitLab 14.1.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEntities_0Test() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        String status = null;
        List<APIEntitiesBulkImports> response = api.listEntities_0()
                .page(page)
                .perPage(perPage)
                .sort(sort)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * List all GitLab Migrations
     *
     * This feature was introduced in GitLab 14.1.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMigrationsTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        String status = null;
        List<APIEntitiesBulkImport> response = api.listMigrations()
                .page(page)
                .perPage(perPage)
                .sort(sort)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Start a new GitLab Migration
     *
     * This feature was introduced in GitLab 14.2.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void startNewMigrationTest() throws ApiException {
        String configurationUrl = null;
        String configurationAccessToken = null;
        List<String> entitiesSourceType = null;
        List<String> entitiesSourceFullPath = null;
        List<String> entitiesDestinationNamespace = null;
        List<String> entitiesDestinationSlug = null;
        List<String> entitiesDestinationName = null;
        List<Boolean> entitiesMigrateProjects = null;
        APIEntitiesBulkImport response = api.startNewMigration(configurationUrl, configurationAccessToken, entitiesSourceType, entitiesSourceFullPath, entitiesDestinationNamespace)
                .entitiesDestinationSlug(entitiesDestinationSlug)
                .entitiesDestinationName(entitiesDestinationName)
                .entitiesMigrateProjects(entitiesMigrateProjects)
                .execute();
        // TODO: test validations
    }

}
